### ISSUE TITLE
ngscope crashed at the step of searching for cell.

### ISSUE THREAD

**Issue by LiuYueHui32** [YaxiongXiePrinceton/NG-Scope#10]
## Issue Description ##
when running `./ngscope` from `build/ngscope/src`, the program crashed at the step of searching for cell.

The following is partial report of exception.

> RF device 'UHD' successfully opened
> Starting AGC thread...
> Tunning receiver to 8026363854599.776 MHz
> Searching for cell...
> /home/lyh/NG-Scope-2.2/lib/src/phy/sync/sync.c:298: Invalid N_id_2=218240944
> /home/lyh/NG-Scope-2.2/lib/src/phy/sync/sync.c:298: Invalid N_id_2=218240944
> /home/lyh/NG-Scope-2.2/lib/src/phy/sync/sync.c:839: Must call srsran_sync_set_N_id_2() first!
> /home/lyh/NG-Scope-2.2/lib/src/phy/ue/ue_sync.c:841: Error finding correlation peak (-1)
> /home/lyh/NG-Scope-2.2/lib/src/phy/ue/ue_cell_search.c:317: Error calling srsran_ue_sync_work()
> /home/lyh/NG-Scope-2.2/lib/src/phy/rf/rf_utils.c:204: Error searching cell
> /home/lyh/NG-Scope-2.2/ngscope/src/dciLib/radio.c:59: Error searching for cell
> terminate called without an active exception

I need further instruction about using ng-scope.

## Setup Details ##
I'm using the latest release version 2.2 on a virtual machine with Ubuntu 16.04, which is builded by `build_trial.sh`. My RF frontend is a USRP B210 and the UHD version is 3.15.0.

**Comment by j0lama** [comment]
The frequency that you are using is 8026363854599.776 MHz is invalid. Make sure NG-Scope is configured to listen to a valid downlink frequency.

**Comment by LiuYueHui32** [comment]
> The frequency that you are using is 8026363854599.776 MHz is invalid. Make sure NG-Scope is configured to listen to a valid downlink frequency.

About another option `rnti` in `config.cfg` file，it seems to be used to match C-RNTI in decoded DCI massages.
Is `rnti` obtained from a certain UE, and how to obtained?
