### ISSUE TITLE
The NGScope cannot receive any samples from UHD although it passes all test cases

### ISSUE THREAD

**Issue by elvinlife** [YaxiongXiePrinceton/NG-Scope#11]
## Issue Description ##
With the latest NG-Scope built and all test cases passed, there's a runtime exception saying there's no received samples from UHD. Therefore, the PBCH channel of the detected cell cannot be decoded. The exception error is as follows:

[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.5.0.0-0ubuntu1~focal1
[INFO] [LOGGING] Fastpath logging disabled at runtime.
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 8000 bytes.
[INFO] [X300] Radio 1x clock: 184.32 MHz
[ERROR] [UHD RF] std::bad_alloc
/home/networklab/yc28/NG-Scope/lib/src/phy/rf/rf_uhd_imp.cc:1339: Error timed out while receiving samples from UHD.
/home/networklab/yc28/NG-Scope/lib/src/phy/ue/ue_sync.c:772: Error receiving samples
/home/networklab/yc28/NG-Scope/lib/src/phy/ue/ue_mib.c:256: Error calling srsran_ue_sync_work()
/home/networklab/yc28/NG-Scope/lib/src/phy/rf/rf_utils.c:138: Error decoding MIB
/home/networklab/yc28/NG-Scope/lib/src/phy/rf/rf_utils.c:263: Could not decode PBCH from CELL ID 28
/home/networklab/yc28/NG-Scope/ngscope/src/dciLib/radio.c:59: Error searching for cell
terminate called without an active exception
--- command='./ngscope/src/ngscope -c config.cfg' version=23.04.0 signal=6 date='04/11/2023 21:58:16' ---
      ./ngscope/src/ngscope(+0x76b8) [0x5604a34d76b8]
      /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7efd46306090]
      /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7efd4630600b]
      /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7efd462e5859]
      /lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e8d1) [0x7efd466bf8d1]
      /lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa37c) [0x7efd466cb37c]
      /lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3e7) [0x7efd466cb3e7]
      /home/networklab/yc28/NG-Scope/build/lib/src/phy/rf/libsrsran_rf_uhd.so(+0x15cd8) [0x7efd4618ccd8]
      /home/networklab/yc28/NG-Scope/build/lib/src/phy/rf/libsrsran_rf_uhd.so(+0x2b2a2) [0x7efd461a22a2]
      /lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0xce) [0x7efd46309fde]
      /home/networklab/yc28/NG-Scope/build/lib/src/phy/rf/libsrsran_rf_uhd.so(+0xe157) [0x7efd46185157]
srsRAN crashed. Please send this backtrace to the developers ...
---  exiting  ---

## Setup Details ##
I'm using USRP X310, and measure multiple bands from both T-Mobile and Verizon cells nearby. The OS is ubuntu20.04, and all required dependent packages from the Wiki are installed.
However, the "cmake ../" shows that I haven't installed the libasn4g(basically libasn4g.so cannot be found). Do you think this [matters?]([error.log](https://github.com/YaxiongXiePrinceton/NG-Scope/files/13420010/error.log))

## Expected Behavior ##
There shoud be at least some samples from the UHD, since the UHD runtime is constructed.

## Actual Behaviour ##
Timeout when receiving any sample

## Additional Information ##
I've attached the config file and complete error log for your reference. Really appreciate it if you can help to check it!

[config.txt](https://github.com/YaxiongXiePrinceton/NG-Scope/files/13420013/config.txt)
[error.log](https://github.com/YaxiongXiePrinceton/NG-Scope/files/13420016/error.log)

**Comment by j0lama** [comment]
libasn lib is a library (currently private) for decoding RRC layer messages (It will decode SIBs in the context of NG-Scope).  This library is not essential for NG-Scope and it will work perfectly without it. 

Have you tried with another USRP model (e.g. B210)?

**Comment by elvinlife** [comment]
I've figured it out that the system crashes when it's in Ubuntu20.04, and it works well in Ubuntu16. Maybe more testing is required for Ubuntu20.04
